version: "3"

services:
  app:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/opt/poc
    command: python /opt/poc/main.py
    network_mode: host